apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: radarr
  name: radarr
spec:
  replicas: 5
  selector:
    matchLabels:
      app: radarr
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - image: linuxserver/radarr:latest
        name: radarr
        resources:
          limits:
            cpu: "0.5"
            memory: 256Mi
          requests:
            cpu: "0.25"
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /
            port: 7878
          initialDelaySeconds: 10 
          periodSeconds: 10 
          timeoutSeconds: 5 
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 7878
          initialDelaySeconds: 10
          periodSeconds: 10 
          timeoutSeconds: 5 
          failureThreshold: 3
          successThreshold: 1
        startupProbe:
          tcpSocket: 
            port: 7878
          initialDelaySeconds: 10
          timeoutSeconds: 5 
          failureThreshold: 1
          
